// Sämtliche deutschen UI-Texte an einem Ort.

export const STR = {
  pickUp: 'E: Aufheben',
  climbHint: 'Leiter: Blick hoch/runter · Leertaste: loslassen',
  catchFish: 'E: Fangen',
  useCraftingTable: 'E: Werkbank benutzen',
  craftingTitle: 'Werkbank',
  crafted: (name: string) => `${name} hergestellt!`,
  dismantled: 'Fass zerlegt!',
  dismantleBlocked: 'Zum Zerlegen muss das Feld leer sein',
  fuelFound: (l: number) => `Treibstofffass: +${l} L Treibstoff`,
  fuelLabel: (l: number) => `Treibstoff: ${l} L`,
  gegessen: (name: string, plus: number) => `${name} gegessen (+${plus} Nahrung)`,
  erschoepft: 'Du bist erschöpft – iss etwas!',
  sharkBite: (dmg: number) => `Haiangriff! -${dmg} Leben`,
  sharkRepelled: 'Hai vertrieben!',
  monsterHitShip: (n: number, max: number) => `Das Seemonster rammt das Schiff! (${n}/${max})`,
  shipSinking: 'Das Schiff sinkt!',
  drownedTitle: 'DU BIST ERTRUNKEN',
  diedTitle: 'DU BIST GESTORBEN',
  monsterDeathTitle: 'DAS SEEMONSTER HAT DICH ERWISCHT',
  shipSunkTitle: 'DAS SCHIFF IST GESUNKEN',
  bossSurfaced: 'Das Wasser bebt – etwas Kolossales taucht auf!',
  bossSwallowedTitle: 'DAS BOOT WURDE VERSCHLUCKT',
  leben: 'Leben',
  nahrung: 'Nahrung',
  luft: 'Luft',
  locked: 'Versperrt',
  engineBroken: 'Motor (defekt)',
  motorRepairTitle: 'Motor-Reparatur',
  motorApply: 'E: Material anwenden',
  motorRunning: 'Motor läuft!',
  motorNothingToApply: 'Benötigtes Material in der Hotbar auswählen',
  motorApplied: (name: string, n: number) => `${n}x ${name} verbaut`,
  motorFuelApplied: (l: number) => `+${l} L Treibstoff eingefüllt`,
  motorComplete: 'Der Motor brummt! Die Brücke ist jetzt zugänglich.',
  helmUse: 'E: Steuer übernehmen',
  helmStop: 'W/S: Fahrhebel · A/D: Steuerrad · E: Steuer loslassen',
  helmNoMotor: 'Steuerstand (der Motor läuft nicht)',
  loadNotAvailable: 'Spiel laden ist noch nicht verfügbar.',
  quitBrowserHint: 'Zum Beenden bitte den Browser-Tab schließen.',
  inventoryFull: 'Inventar voll!',
  hotbarFull: 'Schnellinventar voll!',
  pickedUp: (name: string) => `${name} +1`,
  itemNames: {
    holzplanke: 'Holzplanke',
    eisen: 'Eisen',
    fisch: 'Fisch',
    grossfisch: 'Großer Fisch',
    gold: 'Gold',
    fass: 'Fass',
    hammer: 'Hammer',
    nyzerin: 'Nyzerin',
    glyzerin: 'Glyzerin',
    stein: 'Stein',
    nahrung: 'Nahrung',
    plastik: 'Plastik',
    telefon: 'Telefon',
  } as Record<string, string>,
} as const;
