// Sämtliche deutschen UI-Texte an einem Ort.

export const STR = {
  pickUp: 'E: Aufheben',
  climbHint: 'Leiter: Blick hoch/runter · Leertaste: loslassen',
  catchFish: 'E: Fangen',
  useCraftingTable: 'E: Werkbank benutzen',
  craftingTitle: 'Werkbank',
  crafted: (name: string) => `${name} hergestellt!`,
  dismantled: 'Fass zerlegt!',
  dismantleBlocked: 'Zum Zerlegen muss das Feld leer sein',
  fuelFound: (l: number) => `Treibstofffass: +${l} L Treibstoff`,
  fuelLabel: (l: number) => `Treibstoff: ${l} L`,
  gegessen: (name: string, plus: number) => `${name} gegessen (+${plus} Nahrung)`,
  erschoepft: 'Du bist erschöpft – iss etwas!',
  sharkBite: (dmg: number) => `Haiangriff! -${dmg} Leben`,
  sharkRepelled: 'Hai vertrieben!',
  drownedTitle: 'DU BIST ERTRUNKEN',
  diedTitle: 'DU BIST GESTORBEN',
  leben: 'Leben',
  nahrung: 'Nahrung',
  luft: 'Luft',
  locked: 'Versperrt',
  engineBroken: 'Motor (defekt)',
  radioDead: 'Funkgerät (ohne Strom)',
  loadNotAvailable: 'Spiel laden ist noch nicht verfügbar.',
  quitBrowserHint: 'Zum Beenden bitte den Browser-Tab schließen.',
  inventoryFull: 'Inventar voll!',
  hotbarFull: 'Schnellinventar voll!',
  pickedUp: (name: string) => `${name} +1`,
  itemNames: {
    holzplanke: 'Holzplanke',
    eisen: 'Eisen',
    fisch: 'Fisch',
    grossfisch: 'Großer Fisch',
    gold: 'Gold',
    fass: 'Fass',
    hammer: 'Hammer',
    nyzerin: 'Nyzerin',
    glyzerin: 'Glyzerin',
    stein: 'Stein',
    nahrung: 'Nahrung',
    plastik: 'Plastik',
  } as Record<string, string>,
} as const;
